---
- name: Test temp files in AAP2
  hosts: all
  gather_facts: no
  vars:
    controller_machine: ansible-1
  tasks:

    - name: Create SSH key file
      tempfile:
        state: file
        suffix: ssh_key_file
      run_once: true
      register: backup_manager_git_deploy_key_file
      delegate_to: "{{ controller_machine }}"

    - name: "Generate key_file"
      run_once: true
      copy:
        content: "ssh key stuff...."
        dest: "{{ backup_manager_git_deploy_key_file.path }}"
        mode: 0600
      delegate_to: "{{ controller_machine }}"

    - name: contents of file
      run_once: true
      debug:
        msg: "{{ lookup('file', backup_manager_git_deploy_key_file['path']) }}"
      delegate_to: "{{ controller_machine }}"
