---
- name: ADD A NEW LOOPACK INTERFACE
  eos_interface:
    name: Loopback100
    enabled: True

- name: CONFIGURE LOOPBACK 100
  eos_interface:
      name: Loopback100
      description: Managed by Ansible

- name: CONFIGURE AN IPv4 address
  eos_l3_interface:
    name: loopback100
    ipv4: 192.168.0.1/24
