---
- name: ADD A NEW LOOPACK INTERFACE
  eos_interface:
    name: Loopback100
    enabled: True

- name: CONFIGURE LOOPBACK 100
  eos_interface:
      name: Loopback100
      description: Managed by Ansible
      speed: 100full
      mtu: 512
